// Generated by CoffeeScript 1.10.0
var Cursor, Logger, Type, childProcess, hook, type;

require("isNodeJS");

if (isNodeJS) {
  childProcess = require("child_process");
}

Logger = require("Logger");

Type = require("Type");

hook = require("hook");

Cursor = require("./Cursor");

type = Type("MainLogger");

type.inherits(Logger);

type.optionDefaults = isNodeJS ? {
  process: global.process
} : void 0;

type.defineValues({
  cursor: function() {
    return Cursor(this);
  }
});

type.initInstance(function() {
  require("temp-log")._ = this;
  return hook.after(this, "_printChunk", function(result, chunk) {
    if (chunk.message === this.ln) {
      return this.cursor._x = 0;
    } else {
      return this.cursor._x += chunk.length;
    }
  });
});

type.overrideMethods({
  __willClear: function() {
    if (!(isNodeJS && this.process)) {
      return;
    }
    this.cursor._x = this.cursor._y = 0;
    return this._print(childProcess.execSync("printf '\\33c\\e[3J'", {
      encoding: "utf8"
    }));
  },
  __willClearLine: function(line) {
    var isCurrentLine, message;
    if (!(isNodeJS && this.process)) {
      return;
    }
    isCurrentLine = line.index === this._line;
    if (isCurrentLine) {
      this.cursor.x = 0;
    } else {
      this.cursor.save();
      this.cursor.move({
        x: 0,
        y: line.index
      });
    }
    message = repeatString(" ", line.length);
    this._printToChunk(message, {
      line: line.index,
      hidden: true
    });
    if (isCurrentLine) {
      return this.cursor.x = 0;
    } else {
      return this.cursor.restore();
    }
  }
});

module.exports = type.construct();
